name: Compile All Maps

on:
  workflow_call:
    inputs:
      max_required_byond_client:
        required: true
        type: string

jobs:
  compile_all_stations:
    name: Compile All Station Maps
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup_bun

      - name: Restore BYOND from Cache
        uses: ./.github/actions/restore_or_install_byond
        
      - name: Install BYOND dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev:i386

      - name: Compile All Maps
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build.sh --ci dm -DCIBUILDING -DCITESTING -DALL_MAPS
    
      - name: Check client Compatibility
        uses: tgstation/byond-client-compatibility-check@v3
        with:
          dmb-location: roguetown.dmb
          max-required-client-version: ${{inputs.max_required_byond_client}}

  compile_all_templates:
    name: Compile All Templates
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup_bun

      - name: Restore BYOND from Cache
        uses: ./.github/actions/restore_or_install_byond

      - name: Install BYOND dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev:i386

      - name: Compile All Templates
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build.sh --ci dm -DCIBUILDING -DCITESTING -DALL_TEMPLATES

  compile_all_dungeons:
    name: Compile All Dungeons
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup_bun

      - name: Restore BYOND from Cache
        uses: ./.github/actions/restore_or_install_byond

      - name: Install BYOND dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev:i386

      - name: Compile All Dungeons
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build.sh --ci dm -DCIBUILDING -DCITESTING -DALL_DUNGEONS
